### ISSUE TITLE
Non-transparent background feature

### ISSUE THREAD

**Issue by JulianHaugeneder** [khmyznikov/pwa-install#1]
It would be great if there was an option for the iOS modal to make the background non-transparent. 
It's difficult to customize this yourself because of the shadow dom. 

Great project so far!

**Comment by khmyznikov** [comment]
Hi @JulianHaugeneder. Thanks!
It was bug, I found this last week. There is CSS blur property that doesn't work without webkit suffix. Anyway, I just released new 0.1.0 version, many good improvements and fixes, could you please take a look?

**Comment by khmyznikov** [comment]
@JulianHaugeneder even more updates already came, compatibility improved and more fixes. Will be glad to hear your feedback.

**Comment by khmyznikov** [comment]
Fixed
