### ISSUE TITLE
support chrome on iOS

### ISSUE THREAD

**Issue by supa-thibaud** [khmyznikov/pwa-install#102]
Now chrome on iOS can add to homescreen.
Do you plan to remove the "safari" step on the instructions?

**Comment by khmyznikov** [comment]
Yeah, need to be added 👍

**Comment by VersionReview** [comment]
just a suggestion: would be nice to help user to "find" the share symbol. i recognized that MANY (37%) of Apple user didnt find the share symbol. many non techies just dont know what a share symbol is, what a navigation bar is etc...

so perhaps also have some arrows or something to show those user the "entry" - so the share symbol - to help them install the app on ios

**Comment by jalamprea** [comment]
Hey, @khmyznikov, any idea if this change will be added soon? if not, I can help with the PR

**Comment by khmyznikov** [comment]
Added in 0.5.0
Happy new year!🎄
