### ISSUE TITLE
beforeinstallprompt Event Firing After big delay (10+ Seconds)

### ISSUE THREAD

**Issue by capmorganbih** [khmyznikov/pwa-install#103]
I’m encountering an issue where the beforeinstallprompt event on Android is delayed by around 10 seconds after the page loads. Ideally, I would like to trigger the install prompt immediately when the page is hit, but it seems to take quite a while to fire. Is there any way to speed up the triggering of this event?

Thank you for your help

**Comment by khmyznikov** [comment]
It's the browser that triggers this event. You can only indirectly influence it, for example, by pushing the user to press some buttons or scroll in your application. Basically, some interactions from user required to trigger this event. Overall, it's anti-pattern to ask the user immidiately to install your app. Same thing for permissions for notifications or similar.

**Comment by khmyznikov** [comment]
@MatanMaimon there's many different metrics. My demo page is very simple and loads fast. That's one of the reasons. Another is you might already engaged with the page (clicked buttons and etc), browser remembers that and reduce delay.
