### ISSUE TITLE
Unable to Render PWAInstall Component with Refine - Blank Screen with No Console Errors

### ISSUE THREAD

**Issue by Samuel-Muriuki** [khmyznikov/pwa-install#104]
Hi, I am currently facing a **blank screen** issue when trying to render the PWAInstall component from the @khmyznikov/pwa-install package in my React application. I have isolated the component and removed other dependencies, but the issue persists.

I suspect that the problem might be related to using the refine package in my project. Here are a few details:

1. The PWAInstall component does not render anything on the screen, and there are no console errors.
2. The issue occurs even when rendering the PWAInstall component in a minimal setup.

I have reproduced the issue here on [Stackblitz](https://stackblitz.com/edit/vite-react-ts-nwpbhs?file=src%2FApp.tsx
).

Here is the full list of packages used:
` npm ls
myProject
+-- @khmyznikov/pwa-install@0.4.8

+-- @refinedev/antd@5.43.1

+-- @refinedev/cli@2.16.39

+-- @refinedev/core@4.55.0

+-- @refinedev/react-router-v6@4.6.0

+-- @types/react-dom@18.0.1

+-- @types/react@18.0.5

+-- @vitejs/plugin-react@1.3.1

+-- antd@5.21.6

+-- esbuild-linux-64@0.14.36 extraneous

+-- react-dom@18.0.0

+-- react-router-dom@6.27.0

+-- react@18.0.0

+-- typescript@5.5.3

`-- vite@2.9.5`

**Comment by khmyznikov** [comment]
Sorry I'm not familiar with refined and how it can affect. Did you tried this example? https://stackblitz.com/edit/vite-react-ts-2eeiak?file=src%2FApp.tsx

**Comment by khmyznikov** [comment]
I've just tried to remove the pwa-install completely from your sample and still have the empty page, so not sure what's wrong with your demo.

**Comment by Samuel-Muriuki** [comment]
Hi @khmyznikov , I was away but I have made the necessary changes to have a minimalistic view of the app. Here is the update on [StackBlitz](https://stackblitz.com/edit/vite-react-ts-nwpbhs?file=src%2Fhome%2Flist.tsx)

**Comment by Samuel-Muriuki** [comment]
> Sorry I'm not familiar with refined and how it can affect. Did you tried this example? https://stackblitz.com/edit/vite-react-ts-2eeiak?file=src%2FApp.tsx

Yes, I have tried it and just used that in my example app below:

> Hi @khmyznikov , thank you for your response. I was away, but I have made the necessary changes to have a minimalistic view of the app. Here is the update on [StackBlitz](https://stackblitz.com/edit/vite-react-ts-nwpbhs?file=src%2Fhome%2Flist.tsx).
> 
> **The PWAInstall Component is now rendered with Refine. The prompt appears, but it doesn’t trigger the app installation.**

**Comment by Samuel-Muriuki** [comment]
@khmyznikov , there have been **2 similar issues** that were raised before but **none provided a solid solution for the fix**.

1. [**Failed to execute 'define' on 'CustomElementRegistry' [BUG]** `#20`](https://github.com/khmyznikov/pwa-install/issues/20
)

2. [ **index-x570lffi-17260…me=1726045177091:63 NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry': the name "pwa-gallery" has already been used with this registry** `#82`](https://github.com/khmyznikov/pwa-install/issues/82)

**Comment by khmyznikov** [comment]
@Samuel-Muriuki 
![image](https://github.com/user-attachments/assets/4897f275-bedb-4a36-af84-3c33fa8a2602)

**Comment by Samuel-Muriuki** [comment]
@khmyznikov , this has been fixed [**StackBlitz**](https://stackblitz.com/edit/vite-react-ts-nwpbhs?file=src%2Fhome%2Flist.tsx).


>  ![image](https://private-user-images.githubusercontent.com/6115884/384030886-4897f275-bedb-4a36-af84-3c33fa8a2602.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNDQwOTIsIm5iZiI6MTczMTA0Mzc5MiwicGF0aCI6Ii82MTE1ODg0LzM4NDAzMDg4Ni00ODk3ZjI3NS1iZWRiLTRhMzYtYWY4NC0zYzMzZmE4YTI2MDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDhUMDUyOTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjcyMDhkMzNlYjRhZDdhZjc1YzUyYTQ5NDAwYTBlNWU4YTAzYmVmZWM3Zjc3YTM4MTZjYjlkMTk0NDdkOWU4NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.97K4BiXcJUcs3WL3KRtaer0V-hxHD8OCCkz9N90HP4Q)

**Comment by khmyznikov** [comment]
@Samuel-Muriuki  https://stackblitz.com/edit/vite-react-ts-w3yxfp?file=src%2Fhome%2Flist.tsx

**Comment by Samuel-Muriuki** [comment]
This is the error I see on my console while working from my machine;
**`Uncaught NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry': the name "pwa-gallery" has already been used with this registry`**
On the minimized [StackBlitz](https://stackblitz.com/edit/vite-react-ts-nwpbhs?file=src%2Fhome%2Flist.tsx) example, the pwa popup for install is shown, but doesn't trigger an installation when clicked.
Kindly help me figure how to get these fixed:
1. Get rid of the error in my console.
2. Trigger the installation on button click.

> @khmyznikov , this has been fixed [**StackBlitz**](https://stackblitz.com/edit/vite-react-ts-nwpbhs?file=src%2Fhome%2Flist.tsx).
> 
> > ![image](https://private-user-images.githubusercontent.com/6115884/384030886-4897f275-bedb-4a36-af84-3c33fa8a2602.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNDQwOTIsIm5iZiI6MTczMTA0Mzc5MiwicGF0aCI6Ii82MTE1ODg0LzM4NDAzMDg4Ni00ODk3ZjI3NS1iZWRiLTRhMzYtYWY4NC0zYzMzZmE4YTI2MDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDhUMDUyOTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjcyMDhkMzNlYjRhZDdhZjc1YzUyYTQ5NDAwYTBlNWU4YTAzYmVmZWM3Zjc3YTM4MTZjYjlkMTk0NDdkOWU4NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.97K4BiXcJUcs3WL3KRtaer0V-hxHD8OCCkz9N90HP4Q)

**Comment by khmyznikov** [comment]
@Samuel-Muriuki I've showed you it works. You need to import the component only once; this is why you see the CustomElementRegistry error. Installation flow inside the stackblitz most probably will not work, because it's not a standalone web app but the iframe. You can try to open the preview in separate tab, but I have only infinite loading, can't verify it will help.
