### ISSUE TITLE
Svelte Example

### ISSUE THREAD

**Issue by nijat** [khmyznikov/pwa-install#106]
Is there an example of how to use this in Svelte? I tried, but I couldn't get it to work. It would be great to see a simple example of how to show a dialog.

**Comment by khmyznikov** [comment]
Try this https://github.com/sveltejs/svelte/issues/7334

**Comment by khmyznikov** [comment]
https://stackblitz.com/edit/svelte-tab-2-sng9wa?file=src%2Froutes%2F%2Bpage.svelte
