### ISSUE TITLE
"Banner not shown" Error Due to beforeinstallprompt Handling

### ISSUE THREAD

**Issue by jason5ng32** [khmyznikov/pwa-install#113]
I'm encountering an error message in the console related to the handling of the beforeinstallprompt event:

> Banner not shown: beforeinstallpromptevent.preventDefault() called. The page must call beforeinstallpromptevent.prompt() to show the banner.

This issue seems to be related to recent changes in newer versions of Chrome regarding Progressive Web App (PWA) installation behavior.

While this error does not currently prevent me from manually triggering the installation prompt using the pwa-install component's provided UI, the persistent error message in the console is undesirable.

Is there a recommended solution or workaround to resolve this error message and ensure proper handling of the beforeinstallprompt event within the pwa-install component? Any guidance or assistance would be greatly appreciated.

**Comment by khmyznikov** [comment]
I don't remember any recent changes in Chrome about that, can you share the link?

**Comment by jason5ng32** [comment]
I don't know if there was a change log about that.

I am using  Chrome for Mac 131.0.6778.205, and when I open your demo page: https://khmyznikov.com/pwa-install/ , I got the same warning on the dev console:

![chrome](https://github.com/user-attachments/assets/49c0ef2e-03ff-422c-953a-39976fde4c5e)

**Comment by khmyznikov** [comment]
Oh I see, that's not an issue. We call preventDefault to catch the browser event and override with our own behavior. So that's not a warning, just some info message from the browser.

**Comment by jason5ng32** [comment]
All right, thank you.
