### ISSUE TITLE
Vue Support

### ISSUE THREAD

**Issue by vdiaza** [khmyznikov/pwa-install#17]
I have been trying to install this in my Vue3 app, but I haven't been able to succeed.

The <pwa-install> element does not provide the functions or variables needed when I load the app.

**Comment by khmyznikov** [comment]
@vdiaza hey! Do you figured out?

**Comment by vdiaza** [comment]
@khmyznikov yes! totally my bad, I had forgotten to import it. using `import '@khmyznikov/pwa-install';`
