### ISSUE TITLE
Failed to execute 'define' on 'CustomElementRegistry' [BUG]

### ISSUE THREAD

**Issue by vdiaza** [khmyznikov/pwa-install#20]
I have been getting this error lately

`Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "pwa-gallery" has already been used with this registry`

I am not sure why is this happening, but only happens on production. I am not able to reproduce in localhost, I am guessing that is due to the web manifest.

**Comment by khmyznikov** [comment]
@vdiaza sounds like duplicate dependencies problem.
`npx find-duplicate-dependencies`

**Comment by vdiaza** [comment]
Nope, it didn't find any duplicates related to this. I feel that must be something related to vue/vite by loading twice the script... still looking around.

**Comment by khmyznikov** [comment]
@vdiaza are you figured out?

**Comment by vdiaza** [comment]
> @vdiaza are you figured out?

Yes, figure it out recently. It had nothing to do with this code. It was all related to the [webfontloader](https://www.npmjs.com/package/webfontloader) which happen to be calling the JS file again after being already called. But its all figured out. 

Thanks!
