### ISSUE TITLE
Install button isn't doing anything; not saving as app in Chrome on mobile

### ISSUE THREAD

**Issue by Mennez** [khmyznikov/pwa-install#25]
I have implemented this nice plugin for our website to add it as an web app. It works fine on iOS with the dialog and also on Android the dialog is shown. However the install functionality does not work at all on my Google Pixel phone on chrome, but the demo version is working perfectly fine.

I am not sure what I am doing wrong, since I followed all the instructions of the plugin and also added the manifest file like this:

```
{
 "name": "Clashflash",
 "description": "In the mood for a game? Play all our (flash) indie games in one web app for the most immersive experience!",
 "scope": "/",
 "display": "standalone",
 "icons": [
  {
   "src": "/icon/android-icon-192x192.png",
   "type": "image/png",
   "sizes": "192x192",
   "purpose": "maskable any"
  },
  {
   "src": "/icon/android-icon-512x512.png",
   "type": "image/png",
   "sizes": "512x512",
   "purpose": "maskable any"
  },
  {
   "src": "\/android-icon-36x36.png",
   "sizes": "36x36",
   "type": "image\/png",
   "density": "0.75"
  },
  {
   "src": "\/android-icon-48x48.png",
   "sizes": "48x48",
   "type": "image\/png",
   "density": "1.0"
  },
  {
   "src": "\/android-icon-72x72.png",
   "sizes": "72x72",
   "type": "image\/png",
   "density": "1.5"
  },
  {
   "src": "\/android-icon-96x96.png",
   "sizes": "96x96",
   "type": "image\/png",
   "density": "2.0"
  },
  {
   "src": "\/android-icon-144x144.png",
   "sizes": "144x144",
   "type": "image\/png",
   "density": "3.0"
  },
  {
   "src": "\/android-icon-192x192.png",
   "sizes": "192x192",
   "type": "image\/png",
   "density": "4.0"
  }
 ]
}
```

Our website with the plugin implemented is available online: [clashflash.com](https://www.clashflash.com/)

**Comment by khmyznikov** [comment]
This is because your manifest have issues. You need to fix them first:
![image](https://github.com/khmyznikov/pwa-install/assets/6115884/7d09ceda-8b0b-49f3-8fed-2cd4c74688ac)
And then just wait for installation available event from the component and then show your custom dialog.

**Comment by Mennez** [comment]
Thanks a lot! Seems to be working now.
