### ISSUE TITLE
How import it for Angular ?

### ISSUE THREAD

**Issue by wawefood** [khmyznikov/pwa-install#27]
Hi, I'm trying to use your package without success in my angular project. Despite the import, the pwa-install component is not define. 
Thanks a lot

**Comment by khmyznikov** [comment]
Hi! Did you tried this way? https://academind.com/tutorials/web-components-introduction/#consuming-the-web-component-in-angular

**Comment by khmyznikov** [comment]
@wawefood any luck?

**Comment by khmyznikov** [comment]
@wawefood https://github.com/khmyznikov/pwa-install/discussions/40
