### ISSUE TITLE
Apple doesn't respect start_url

### ISSUE THREAD

**Issue by s0xDk** [khmyznikov/pwa-install#36]
Consider using `history.pushState({}, '', start_url)` when user opens "How To For Apple".
This way PWA would be installed with the proper `start_url` on Apple devices.

**Comment by khmyznikov** [comment]
Hi! Any potential drawbacks?

**Comment by s0xDk** [comment]
Actually, `history.replaceState` is a better option ;)
Nicely done! ✨

**Comment by khmyznikov** [comment]
Fixed
