### ISSUE TITLE
One more step for iOS instruction

### ISSUE THREAD

**Issue by s0xDk** [khmyznikov/pwa-install#38]
In all (most?) cases, "Add to Home Screen" button is hidden under the bottom edge of the screen and Share Panel must be scrolled down to reveal that button.

Suggesting to add "Scroll Down" step between "Press Share in Navigation bar" and "Press Add to Home Screen".

1) Open in Safari browser _(maybe hide this item if user is already in Safari? 🤔)_
2) Press Share in Navigation bar
3) **Scroll Down** 👈
4) Press Add to Home Screen

**Comment by khmyznikov** [comment]
1. You can't hide it because of existence SFSafariViewController
![image](https://github.com/khmyznikov/pwa-install/assets/6115884/58c101fb-4ec8-400e-9aae-913fa3b71a99)
AFAIK you can't add to home screen from this state. And detect this state not sure is possible...

**Comment by s0xDk** [comment]
I mean, after clicking on the Share button in the nav bar, user can't see "Add to Home Screen" button and needs to scroll down to find it.

<img width="468" alt="Screenshot 2024-01-13 at 18 50 43" src="https://github.com/khmyznikov/pwa-install/assets/44265/ee522643-af7b-4817-8a88-4d7fb56b4b3f">

**Comment by khmyznikov** [comment]
Yeah I got this point. But do you think it's a real problem? Have any real life experience or just a clue?

**Comment by s0xDk** [comment]
Noticed that when explained to my friends how to install my PWA.
2 of 3 told me that they "don't see Add to Home Screen button" 🫠
I think the problem is real for not-so-technically savvy users.

**Comment by s0xDk** [comment]
@khmyznikov also check this project out:
https://github.com/philfung/add-to-homescreen

<img width="373" alt="Screenshot 2024-01-13 at 19 45 06" src="https://github.com/khmyznikov/pwa-install/assets/44265/84956074-5d57-4a3a-9f15-a11f070583b4">

**Comment by khmyznikov** [comment]
@s0xDk nice project. Interesting why he is not reached me to collaborate.

**Comment by s0xDk** [comment]
@khmyznikov I like how it detects different kinds of Safari WebViews and points an arrow to right places.

**Comment by s0xDk** [comment]
One more thing:
If a user is already within Safari, step “1) Open in Safari browser” may be misleading.

So the instruction could be updated to this:

1) Press Share in Navigation bar
2) Scroll Down the Share menu
3) Press Add to Home Screen

**Comment by khmyznikov** [comment]
Maybe:
1. Press Share in Navigation bar
2. Scroll down to Add to Home Screen

**Comment by s0xDk** [comment]
> Maybe:
> 
> 1. Press Share in Navigation bar
> 2. Scroll down to Add to Home Screen

Yeah, it's more concise and keeps the point.

**Comment by zehawki** [comment]
Here's how I do it:

**Comment by zehawki** [comment]
Here's how I do it:

![image](https://github.com/khmyznikov/pwa-install/assets/8095144/dcc7aa71-2477-4095-8a13-1fadba4316b3)

The language is directly borrowed from Apple - https://support.apple.com/en-sg/guide/iphone/iph42ab2f3a7/ios

**Comment by cillian-cwb** [comment]
> In all (most?) cases, "Add to Home Screen" button is hidden under the bottom edge of the screen and Share Panel must be scrolled down to reveal that button.
> 
> Suggesting to add "Scroll Down" step between "Press Share in Navigation bar" and "Press Add to Home Screen".
> 
> 1. Open in Safari browser _(maybe hide this item if user is already in Safari? 🤔)_
> 2. Press Share in Navigation bar
> 3. **Scroll Down** 👈
> 4. Press Add to Home Screen



> In all (most?) cases, "Add to Home Screen" button is hidden under the bottom edge of the screen and Share Panel must be scrolled down to reveal that button.
> 
> Suggesting to add "Scroll Down" step between "Press Share in Navigation bar" and "Press Add to Home Screen".
> 
> 1. Open in Safari browser _(maybe hide this item if user is already in Safari? 🤔)_
> 2. Press Share in Navigation bar
> 3. **Scroll Down** 👈
> 4. Press Add to Home Screen



> In all (most?) cases, "Add to Home Screen" button is hidden under the bottom edge of the screen and Share Panel must be scrolled down to reveal that button.
> 
> Suggesting to add "Scroll Down" step between "Press Share in Navigation bar" and "Press Add to Home Screen".
> 
> 1. Open in Safari browser _(maybe hide this item if user is already in Safari? 🤔)_
> 2. Press Share in Navigation bar
> 3. **Scroll Down** 👈
> 4. Press Add to Home Screen

As iOS Chrome and Edge now supports 'Add to Home Screen' there is no need for '1. Open in Safari browser'.

**Comment by khmyznikov** [comment]
Added in 0.5.0
Happy new year! 🎄
