### ISSUE TITLE
Add support mobile Firefox

### ISSUE THREAD

**Issue by denysdesign** [khmyznikov/pwa-install#39]
Hello,
Please add support Firefox mobile👍

Thank you!

**Comment by khmyznikov** [comment]
For Android? Maybe you are interested in contributing?
I think the Bottom Sheet component can be adapted to show small instructions like: Tap three dots, Tap "Install".

**Comment by SamLeatherdale** [comment]
This could be helpful for Chrome Android as well.

I know this library already has the Chrome Android native install option for when the browser prompts user for install, but if it decides not to and you just want to ask the user to manually install it, you can do so via the 3 dot menu > Install app (or Add to Home screen if it doesn't have a manifest).

**Comment by khmyznikov** [comment]
Added in 0.5.0
Happy new year! 🎄
