### ISSUE TITLE
The react polyfill demo linked in README is broken

### ISSUE THREAD

**Issue by riesentoaster** [khmyznikov/pwa-install#44]
<img width="1512" alt="image" src="https://github.com/khmyznikov/pwa-install/assets/27142200/088bb09b-52fe-441e-a13c-c1dc28223632">

While trying to add it to my project (see also #43), I found that importing `/src/fallback/react` seems to work.

**Comment by khmyznikov** [comment]
@riesentoaster can you check once again? Works for me at least. Idk what's the issue was...

**Comment by riesentoaster** [comment]
Works now, no idea what broke before. Thank you for the response anyways!

**Comment by zehawki** [comment]
Broken again:

![image](https://github.com/khmyznikov/pwa-install/assets/8095144/b44947e2-5d5c-42a0-a70e-5a5cb45726b0)
