### ISSUE TITLE
Allow disable button to close the modal

### ISSUE THREAD

**Issue by jalamprea** [khmyznikov/pwa-install#48]
One of the requirements from some clients is they want to allow access to their PWA only if the app is installed, if not, it should always ask for the installation.
Currently, there is no way to hide/disable the button to close the modal, so if users tap on the close icon, they will be able to continue using the app without installing it.
Having an option like `disableClose` with `false` as the default value, so it will be always available, but allowing users to change it to `true` will fix this simple use case.

**Comment by jalamprea** [comment]
@khmyznikov  Check the PR and let me know if this behavior looks good for you

**Comment by khmyznikov** [comment]
LGTM! 🤝
