### ISSUE TITLE
If the description in manifest.json is unset or empty, there is no margin below the icon

### ISSUE THREAD

**Issue by howyi** [khmyznikov/pwa-install#53]
I've encountered an issue where the margin below the icon appears to be 0, creating a visual inconsistency when the description field in the manifest.json file is either not set or is an empty string. [Given that the description field is optional]( https://developer.mozilla.org/ja/docs/Mozilla/Add-ons/WebExtensions/manifest.json/description), I believe the display should still maintain a clean and consistent style even when this field is unset.

Please see the attached images for a clearer understanding of the issue. It seems that the absence or emptiness of the description directly impacts the layout in an unintended way, leading to a lack of spacing where it would normally be expected.
[![Image from Gyazo](https://i.gyazo.com/68bfcc091302fa0c20998ecd4741c2c6.png)](https://gyazo.com/68bfcc091302fa0c20998ecd4741c2c6)
[![Image from Gyazo](https://i.gyazo.com/ff5330bf8c4e12f4da463ad91d45a66e.png)](https://gyazo.com/ff5330bf8c4e12f4da463ad91d45a66e)

It would be appreciated if the styling could be adjusted to ensure that the display remains visually appealing and consistent, regardless of the description field's presence or content in the manifest.json.

**Comment by khmyznikov** [comment]
Please verify if it works good for you now, I'll push new version to npm with this fix + lang.

**Comment by howyi** [comment]
@khmyznikov It worked! thanks for fixing it.
