### ISSUE TITLE
Request to Add an Option to Suppress Pop-ups on Page Load in <pwa-install /> Component

### ISSUE THREAD

**Issue by howyi** [khmyznikov/pwa-install#54]
We prioritize user experience when encouraging the installation of Progressive Web Applications (PWAs) on our website. 

In scenarios where we prefer not to aggressively promote installation, pop-ups that appear every time a page is opened can potentially be perceived as intrusive by users. 

Currently, we are utilizing the "pwa-install" component and wish to address this issue by requesting the addition of an option to suppress the installation prompt pop-ups upon page load. 

Specifically, we would like the installation prompt pop-up to appear only when a user clicks on the install button.
 If there is already an option available that offers this functionality, we would appreciate guidance on how to implement it.

**Comment by khmyznikov** [comment]
Sure, look at this props:
```
manual-apple="true"
manual-chrome="true"
```
I think that's exactly what you need.
