### ISSUE TITLE
Angular 18 compatibility?

### ISSUE THREAD

**Issue by SteveKennedy** [khmyznikov/pwa-install#69]
For some reason, I don't think it works with Angular 18? It was working with 17. 

(Maybe it's something I did...)

![image](https://github.com/khmyznikov/pwa-install/assets/12101125/99318ded-1da8-466a-a48a-11e7e34f10d4)

**Comment by SteveKennedy** [comment]
Oh, maybe, I originally had....

```
  "compilerOptions": {
    "skipLibCheck": true,
```
    
  in the tsconfig.json that hid these issues.....

**Comment by khmyznikov** [comment]
@SteveKennedy yeah just skip the lib check, not sure how to fix it another way...

**Comment by khmyznikov** [comment]
@SteveKennedy I've fixed this. But you need to add types to your tsconfig, check the sample for more info: https://stackblitz.com/edit/aozf92?file=package.json,src%2Fapp%2Fpwa-install%2Fpwa-install.component.html,src%2Fapp%2Fpwa-install%2Fpwa-install.component.ts
