### ISSUE TITLE
Support Opera browser on Android devices

### ISSUE THREAD

**Issue by dotWasim** [khmyznikov/pwa-install#70]
There are bugs that affect the Opera browser on Android devices. You can check the behavior on the demo project using Opera on an Android device:

1. The "Show" button won't display the prompt.
2. Using "Show (force)" will display the prompt.
3. Pressing the "Install" button doesn't show the browser install prompt.

**Comment by khmyznikov** [comment]
It's the same issue https://github.com/khmyznikov/pwa-install/issues/39 . Opera don't have any install promts, so the component can't do anything natively. Need to do the same workaround with instruction as for Safari.

**Comment by khmyznikov** [comment]
Added in 0.5.0
Happy new year! 🎄
