### ISSUE TITLE
Wrong url used for manifest icons and screenshots

### ISSUE THREAD

**Issue by pvo13** [khmyznikov/pwa-install#71]
Version 0.4.0 and newer don't work for me since they generate an incorrect URL for icons and screenshots specified in manifest.json. Version 0.3.9 works fine for me.

The problem is that an language code is added to the URLs that shouldn't be there.
Am I doing something wrong?

**Comment by khmyznikov** [comment]
Which lang urls? I'm not adding them. Last time I changed something around languages: https://github.com/khmyznikov/pwa-install/commit/fe6b308a949a7472377624481f7f4bbde76c57da

Can you share your app url where it's not working?

**Comment by pvo13** [comment]
Sure, here is the link:  https://sportsdate.app

**Comment by khmyznikov** [comment]
I've tested that code manually and don't see any languages in result url...
![image](https://github.com/user-attachments/assets/71985713-db84-4efc-a740-8d5bc464491b)
Can you help me to debug somehow?

**Comment by pvo13** [comment]
I did the same debug session like you with version 0.4.2 
It looks correct in the console, but the final result is incorrect. See the screenshot:
![pwa-install_debug](https://github.com/user-attachments/assets/de1dc8d7-4c3f-4c7b-ab0f-0bb0916428d9)

**Comment by pvo13** [comment]
I did the same debug session like you, now with version 0.4.2. The debug output looks correct, but the app still gives errors, see my screenshot.

![Uploading pwa-install_debug.png…]()

**Comment by khmyznikov** [comment]
What's the manifest url you pass into component? Or you use default? I've repeated your url and don't see any problems... 
![image](https://github.com/user-attachments/assets/db5d6762-1d8f-4982-863f-dd6c72d7e35a)
If you can share the access to your repo, I can debug for myself.

**Comment by pvo13** [comment]
OK, I just found my error. I was missing the slash in the path to manifest.json

`manifest-url="/manifest.json"`
