### ISSUE TITLE
Norwegian localization

### ISSUE THREAD

**Issue by cillian-cwb** [khmyznikov/pwa-install#72]
Norwegian gets default English.  The localization must be 'nb-NO'

**Comment by khmyznikov** [comment]
@AdrianAndersen can you help to figure this out?

**Comment by AdrianAndersen** [comment]
Seems like it is dependent on your device. "no" is just standard Norwegian, while nb-NO (equal to no) and nn-NO (dialectish). I think that all those three should point to the same locale. (Some Norwegians might argue they want a separate one for nn-NO tho, might be better to cross that bridge later and just set it to _one_ Norwegian language)

**Comment by cillian-cwb** [comment]
Tested with pwa-install demo.
well. with Norwegian language chrome iOS (17.5.1) give English. macOS (Sonoma 14.4.1) chrome Norwegian give English. Samsung s8 chrome Norwegian gives English.

Same in Safari iOS.

In my other project I must use nb-NO to get Norwegian. So as Adrian precise, 'nb-NO' should replace 'no'. The nn-NO would need translation first, if implemented as well.

**Comment by AdrianAndersen** [comment]
Yes, that works for me too

**Comment by khmyznikov** [comment]
@cillian-cwb check the [demo page](https://khmyznikov.com/pwa-install/), fixed the nb lang. (update the page a few times after a moment)

**Comment by khmyznikov** [comment]
added in 0.4.3

**Comment by khmyznikov** [comment]
@cillian-cwb can you help me to debug this. Open this page with your devices and copy here the languages lists.
https://ariya.io/demo/language

**Comment by cillian-cwb** [comment]
iPhone NO
Your choice of language is Norwegian Bokmål.
navigator.language | nb-NO
navigator.languages | [nb-NO]
navigator.userLanguage | ?

iPhone ES
Your choice of language is Spanish.
navigator.language | es-ES
navigator.languages | [es-ES]
navigator.userLanguage | ?

Android NO
Your choice of language is Norwegian bokmål.
navigator.language | nb-NO
navigator.languages | [nb-NO, nb, no, nn, en-US,en]
navigator.userLanguage | ?

Edge macOS NO
Your choice of language is Norwegian Bokmål.
navigator.language | nb
navigator.languages | [nb, en]
navigator.userLanguage | ?

Chrome macOS NO
Your choice of language is Norwegian Bokmål.
navigator.language | nb
navigator.languages | [nb]
navigator.userLanguage | ?

Safari macOS EN
Your choice of language is English.
navigator.language | en-GB
navigator.languages | [en-GB]
navigator.userLanguage | ?

DuckDuckGO macOS EN
Your choice of language is English.
navigator.language | en-GB
navigator.languages | [en-GB]
navigator.userLanguage | ?

**Comment by khmyznikov** [comment]
Fixed
