### ISSUE TITLE
URL parameter support

### ISSUE THREAD

**Issue by cillian-cwb** [khmyznikov/pwa-install#79]
Hello.

I have now great control over what I need in pwa-install. Great work @khmyznikov. What it is really needed, is the bundle to support URL parameters. Auto detection work perfectly but it lacks URL parameter support.

I hope you find it to implement it shortly. Thank you.

**Comment by khmyznikov** [comment]
@cillian-cwb Hi! Can you describe more what do you mean, how it should work. I don't think I understand.

**Comment by cillian-cwb** [comment]
> @cillian-cwb Hi! Can you describe more what do you mean, how it should work. I don't think I understand.

Ok. My project can override LocaleID with URL Parameters. For my case, '&language=en-GB', '&language=nb-NO', '&language=es-ES', &language=de-DE' and '&language=fr-FR'. So adding one of these parameters at the end of the URL overrides LocaleID and sets it accordingly.

**Comment by khmyznikov** [comment]
@cillian-cwb the component works with the language from the user's browser. It should be the same, to show the instruction properly.  We had this discussion before and ended with conclusion what's the right way. https://github.com/khmyznikov/pwa-install/pull/43

**Comment by cillian-cwb** [comment]
It works with auto detection yes. But not URL parameters. 

Check yourself: https://khmyznikov.com/pwa-install&language=en-GB

**Comment by khmyznikov** [comment]
Ingen tilpasning for språk er støttet. Fordi brukergrensesnittet til komponenten skal være det samme som brukergrensesnittet til nettleseren.
