### ISSUE TITLE
index-x570lffi-17260…me=1726045177091:63 NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry': the name "pwa-gallery" has already been used with this registry

### ISSUE THREAD

**Issue by cleanown** [khmyznikov/pwa-install#82]
when i add Timestamp to the html js css,the production environment tip index-x570lffi-17260…me=1726045177091:63 NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry': the name "pwa-gallery" has already been used with this registry

**Comment by cleanown** [comment]
![image](https://github.com/user-attachments/assets/a9f448eb-49ce-42af-a0b5-18adff446d6f)

**Comment by khmyznikov** [comment]
Not sure what's the timestamp will do, but it looks like you adding the library multiple times.

**Comment by khmyznikov** [comment]
@cleanown any updates on this?
