### ISSUE TITLE
Some semantics of Chinese are biased

### ISSUE THREAD

**Issue by angelofan** [khmyznikov/pwa-install#86]
The Chinese translation below is inaccurate and needs to be updated.

| English                                                      | Chinese (Current)                                  | Chinese (Recommend)                                  | Why                                                          |
| ------------------------------------------------------------ | -------------------------------------------------- | ---------------------------------------------------- | ------------------------------------------------------------ |
| Less                                                         | 简短资讯                                           | 收起                                                 | The text of a button that hides detailed content when clicked is usually written as "收起". |
| More                                                         | 详细资讯                                           | 更多                                                 | Buttons that reveal more content when clicked usually have text that says "更多". |
| 1) Open in Safari browser                                    | 1) 在Safari上浏览此网页                            | 1) 在 Safari 浏览器中打开此页面                      | There should be a space between the English word and the Chinese word. "Open in [name] browser" is called "在 [name] 浏览器中打开" in many Chinese apps. |
| 2) Press Share in Navigation bar                             | 2) 点击列表上的分享按钮                            | 2) 点击导航栏中的“分享”按钮                          | "列表" is "List". "Navigation bar" should be translated as "导航栏". Clickable text should be enclosed in quotation marks. |
| 3) Press Add to Home Screen                                  | 3) 点击添加到主屏幕                                | 3) 点击“添加到主屏幕”                                | Clickable text should be enclosed in quotation marks.        |
| Hide Instruction                                             | 隐藏安装流程                                       | 隐藏安装步骤                                         | "安装流程" is usually "安装步骤".                            |
| Add to Home Screen                                           | 将App添加到主屏幕                                  | 添加到主屏幕                                         | "将App添加到主屏幕" is "Adding Apps to the Home Screen". "Add to Home Screen" should be translated as "添加到主屏幕". |
| This site has app functionality.                             | 此网站具备app的功能性。                            | 此网站具备 App 功能特性。                            |                                                              |
| Add it to your Dock for extensive experience and easy access. | 将其添加到您的Dock，以享受更全面的体验并便于访问。 | 将其添加到您的程序坞，以享受更全面的体验并便于访问。 | "Dock" should be translated as "程序坞". See the screenshot of Apple's Chinese guide below. |
| Add it to your Home Screen for extensive experience and easy access. | 将其添加到主屏幕，以享受更全面的体验并便于访问。   | 将其添加到主屏幕，以享受更丰富的体验并便于访问。     | "extensive experience" should be translated as "享受丰富的体验". |
| 2) Press Add to Dock                                         | 2) 按下添加到Dock                                  | 2) 点击“添加到程序坞”                                | "Press" is "点击".                                           |
| Add to Dock                                                  | 添加到Dock                                         | 添加到程序坞                                         |                                                              |
| Install it on your device for extensive experience and easy access. | 在您的设备上安装，以享有更全面的体验和便捷的访问。 | 在您的设备上安装，以享受更丰富的体验并便于访问。     | Identical words should keep the same translation.            |

"Dock" in [Apple's Chinese guide](https://support.apple.com/zh-cn/guide/mac-help/mh35859/mac):

> 在 Mac 上使用**程序坞**

![image](https://github.com/user-attachments/assets/560357f1-8eb0-4886-aae9-9553611ac326)

I will create a pull request for this update.

**Comment by khmyznikov** [comment]
Thanks for making PR for this!
