### ISSUE TITLE
Dark mode should only detect "dark" class

### ISSUE THREAD

**Issue by angelofan** [khmyznikov/pwa-install#90]
My website has a button to manually switch between dark and light mode.
The button click event implements the switch by adding or removing the "dark" class to the top level HTML tree.

## Why use Dark Mode by adding a "dark" class?

[Tailwind CSS](https://tailwindcss.com/) recommends doing this. [Dark mode in Tailwind CSS](https://tailwindcss.com/docs/dark-mode):

> Now instead of dark:{class} classes being applied based on prefers-color-scheme, they will be applied whenever the dark class is present earlier in the HTML tree.

> How you add the `dark` class to the `html` element is up to you, but a common approach is to use a bit of JavaScript that reads a preference from somewhere (like localStorage) and updates the DOM accordingly.

```html
<!-- Dark mode not enabled -->
<html>
<body>
  <!-- Will be white -->
</body>
</html>

<!-- Dark mode enabled -->
<html class="dark">
<body>
  <!-- Will be black -->
</body>
</html>
```

## By referring to Tailwind CSS, we can learn some tips.

For dark mode detection, the package should leave the decision to the developer. Package only detecting the `dark` class of the outer DOM. 

Packages should not detect `@media (prefers-color-scheme: dark)`. Since it is read-only, projects cannot change the appearance of components by toggling this value.

## What developers do in their projects

- Automatic switching: listen to `@media (prefers-color-scheme: dark)` and switch the `dark` class.
- Manual switching: dark mode switch button.
- User preferences: local storage, browser session storage, server storage, etc.

## Package only do

The package only needs to add the dark mode CSS to the `dark` class, no other behavior is required.

## More

This issue also resolves #16 .

**Comment by khmyznikov** [comment]
Hey man. The idea of this component is to mimic or be aligned with the browser UI. This concerns the language and dark mode. Because user experience start from this custom dialog and continues in browser UI, and it's important to keep it consistend.

**Comment by angelofan** [comment]
OK, thanks for the clarification. This plugin is designed to complement the browser's capabilities, not to extend functionality to project. I understand now.

**Comment by khmyznikov** [comment]
@angelofan you actually extend your project, but keeping the UX consistent between the app and browser.
