### ISSUE TITLE
Clicking on the screenshot to turn the page does not work as expected

### ISSUE THREAD

**Issue by angelofan** [khmyznikov/pwa-install#92]
Clicking on the screenshot to turn the page does not work as expected.

## 3 mobile screenshots and 2 tablet screenshots.

- `mobile-2` is skipped.

![image](https://github.com/user-attachments/assets/d1b681a2-8383-486b-bc8c-7b290212d472)

## 2 mobile screenshots and 2 tablet screenshots.

- `mobile-2` is skipped.
- `tablet-1` is not centered.
- `tablet-2` is not centered.

![image](https://github.com/user-attachments/assets/f2f5e7e9-4958-48f3-9655-cc4f4ecaf250)

## 4 mobile screenshots and 2 tablet screenshots.

- `mobile-2` is skipped.
- `mobile-4` is skipped.
- `tablet-1` is not centered.
- `tablet-2` is not centered.

![image](https://github.com/user-attachments/assets/90e12bc8-2d62-47e6-b02b-b6ee70007c1b)

## 4 mobile screenshots and 0 tablet screenshots.

- `mobile-2` is skipped when going right.
- Cannot go back to `mobile-1` when going left.

![image](https://github.com/user-attachments/assets/c0f7605d-366c-46d4-9fb7-ac2137dd6e3e)

**Comment by angelofan** [comment]
The above screenshots are from my [Frok Repository](https://github.com/angelofan/pwa-install). I added screenshot IDs for easier debugging.

**Comment by hccullen** [comment]
Hi @angelofan 
I made a PR with what should be a fix for this. If you're able, I'd love for you to test it as well to confirm it solves your issue, then we'll see if the maintainers will approve it too 🤞

**Comment by angelofan** [comment]
I tested. It works as expected.

**Comment by khmyznikov** [comment]
Thanks folks! Will publish the fixed version soon ❤️
