### ISSUE TITLE
Store `pwa-hide-install` in localStorage instead to prevent re-notification all the time

### ISSUE THREAD

**Issue by hccullen** [khmyznikov/pwa-install#93]
Each time I load my app, the PWA install prompt appears even though I have dismissed it. This is because the `pwa-hide-install` value is stored in session storage rather than somewhere more permanent. This may be intentional/desired though?

## Possible Solutions
1. Add a parameter to allow users to switch to localStorage over the current default.
2. Or switch to localStorage entirely. If there is a good reason to re-prompt, user should force the prompt instead. (note this would be a 'breaking' behaviour)

**Comment by khmyznikov** [comment]
Yep that's a good idea. You can use the manual mode, but this can be a parameter I agree.
