### ISSUE TITLE
Screenshots show all device form-factors. Should only show wide/narrow contextually

### ISSUE THREAD

**Issue by hccullen** [khmyznikov/pwa-install#95]
When creating PWA screenshots, you can define whether they are 'wide' or 'narrow'. The browser then contextually only shows the screenshots contextually relevant for your device. This library prompt shows ALL screenshots.

https://developer.mozilla.org/en-US/docs/Web/Manifest/screenshots#form_factor
https://developer.mozilla.org/en-US/docs/Web/Manifest/screenshots#platform

- [ ] To investigate what rules Chrome et al use to show the right screenshot for `form_factor` (screen width?)
- [ ] To investigate use of `platform` parameter as well:

**Comment by khmyznikov** [comment]
Indeed, I have considered this as well. The gallery was initially created from the first versions and received no complaints, which is why I did not continue working on it.
